export {
  createUserSchema,
  updateUserSchema,
  createTicketSchema,
  updateTicketSchema,
  createTicketMessageSchema,
  inboundEmailSchema,
  type CreateUserInput,
  type CreateUserOutput,
  type UpdateUserInput,
  type UpdateUserOutput,
  type CreateTicketInput,
  type CreateTicketOutput,
  type UpdateTicketInput,
  type UpdateTicketOutput,
  type CreateTicketMessageInput,
  type CreateTicketMessageOutput,
  type InboundEmailInput,
  type InboundEmailOutput,
} from '@helpdesk/core';
