export {
  createUserSchema,
  updateUserSchema,
  createTicketSchema,
  updateTicketSchema,
  createTicketMessageSchema,
  inboundEmailSchema,
  ticketSortFieldSchema,
  sortOrderSchema,
  getTicketsQuerySchema,
  type CreateUserInput,
  type CreateUserOutput,
  type UpdateUserInput,
  type UpdateUserOutput,
  type CreateTicketInput,
  type CreateTicketOutput,
  type UpdateTicketInput,
  type UpdateTicketOutput,
  type CreateTicketMessageInput,
  type CreateTicketMessageOutput,
  type InboundEmailInput,
  type InboundEmailOutput,
  type TicketSortField,
  type SortOrder,
  type GetTicketsQueryInput,
  type GetTicketsQueryOutput,
  polishReplySchema,
  type PolishReplyInput,
  type PolishReplyOutput,
  type PaginatedTicketsResponse,
} from '@helpdesk/core';

