export {
  createUserSchema,
  updateUserSchema,
  createTicketSchema,
  updateTicketSchema,
  createTicketMessageSchema,
  inboundEmailSchema,
  ticketSortFieldSchema,
  sortOrderSchema,
  getTicketsQuerySchema,
  type CreateUserInput,
  type CreateUserOutput,
  type UpdateUserInput,
  type UpdateUserOutput,
  type CreateTicketInput,
  type CreateTicketOutput,
  type UpdateTicketInput,
  type UpdateTicketOutput,
  type CreateTicketMessageInput,
  type CreateTicketMessageOutput,
  type InboundEmailInput,
  type InboundEmailOutput,
  type TicketSortField,
  type SortOrder,
  type GetTicketsQueryInput,
  type GetTicketsQueryOutput,
  polishReplySchema,
  type PolishReplyInput,
  type PolishReplyOutput,
  type PaginatedTicketsResponse,
  evaluateInquirySchema,
  autoResolveTicketSchema,
  batchAutoResolveSchema,
  type EvaluateInquiryInput,
  type EvaluateInquiryOutput,
  type AutoResolveTicketInput,
  type AutoResolveTicketOutput,
  type BatchAutoResolveInput,
  type BatchAutoResolveOutput,
  type AutoResolveEvaluationResult,
  type AutoResolveTicketResult,
  type BatchAutoResolveResult,
  type AutoResolveStats,
  type AutoResolveRuleInfo,
  evaluateClassificationSchema,
  classifyTicketSchema,
  batchClassifySchema,
  type EvaluateClassificationInput,
  type EvaluateClassificationOutput,
  type ClassifyTicketInput,
  type ClassifyTicketOutput,
  type BatchClassifyInput,
  type BatchClassifyOutput,
  type TicketClassificationResult,
  type ClassifyTicketResult,
  type BatchClassifyResult,
  type ClassificationStats,
  type ClassificationCategoryInfo,
} from '@helpdesk/core';
